In [11]:
import os 
# using pickle file stored in tranformed obj to transform the test data
import pickle
file_path = ''
with open(path , 'rb') as f:
    obj = pickle.load(f)
data = [[23,23,34,44242,424242,232323,343434,323232]]
obj.transform(data)

array([[2.30000e+01, 2.30000e+01, 3.40000e+01, 4.42420e+04, 4.24242e+05,
        2.32323e+05]])

In [2]:
from housing_project.keys.key import *
URLKEY

'https://figshare.com/ndownloader/files/5976036'

In [1]:
import os
os.getcwd()

'c:\\Users\\Lokesh\\Desktop\\Testing project'

In [2]:
import yaml

# Define your configuration data as a Python dictionary
config_data = {
    'database': {
        'host': 'localhost',
        'port': 5432,
        'username': 'myuser',
        'password': 'mypassword',
        'database_name': 'mydb',
    },
    'logging': {
        'level': 'INFO',
        'file_path': '/var/log/myapp.log',
    },
}

# Convert the dictionary to a YAML string
yaml_string = yaml.dump(config_data, default_flow_style=False)

# Specify the file path where you want to save the YAML configuration
file_path = 'test.yaml'

# Write the YAML string to the file
with open(file_path, 'w') as yaml_file:
    yaml_file.write(yaml_string)

print(f"Configuration saved to {file_path}")


Configuration saved to test.yaml


In [2]:
from utility.util import  write_config
data = { 'candidate_name_2':{
    'name': 'Shantanu',
    'cast': 'Sount',
    'marks': 94     }
}

file_path = 'test.yaml'
write_config(data , file_path)

In [2]:
# how to edit data present in the config.yaml file ( first read and then update then push)
from utility.util import  *
# Creating an dict to update the config.yaml file
data = { 'candidate_name_3' : {
    'name': 'Pankaj',
    'cast': 'Aggarwal',
    'marks': 92
}

}
# after reading the previous config.yaml file 

file_path = 'test.yaml'
yaml_data = read_config(file_path)


# using the update function update the dict we get from the read_config

yaml_data.update(data)

# pushing back the data to the config.yaml file
write_config(yaml_data, file_path)



In [39]:
# updating the information that is present in the config.yaml file

from utility.util import  *

# reading the config.yaml file
file_path = 'test.yaml'
yaml_data = read_config(file_path)


# updating the data with the information of the candidates with the highest score

# highest scoreing info:

highest_score = max([ i['marks'] for i in yaml_data.values()])
higest_score_candidate = [ i for i in yaml_data.values()  if i.get('marks')==highest_score]
yaml_data['best_candidate_info']['name'] = higest_score_candidate[0]['name']

yaml_data['best_candidate_info']['cast'] = higest_score_candidate[0]['cast']

yaml_data['best_candidate_info']['marks'] = higest_score_candidate[0]['marks']





# pushing this list back to the config.yaml file

write_config(yaml_data , file_path)

In [40]:
yaml_data

{'best_candidate_info': {'cast': 'Sount', 'marks': 94.9, 'name': 'Shantanu'},
 'candidate_name_2': {'cast': 'Sount', 'marks': 94.9, 'name': 'Shantanu'},
 'candidate_name_3': {'cast': 'Rana', 'marks': 94.1, 'name': 'Amit'},
 'candidate_name_4': {'cast': 'Aggarwal', 'marks': 94.2, 'name': 'Pankaj'}}

In [22]:
[i['marks'] for i in data.values()]

[80, 94.3, 94.2]

In [30]:
imfo = [ i for i in data.values() if i.get('marks') == max_marks]
type(imfo[0])

dict

In [70]:
    from utility.util import *
    file_path = 'model_status.yaml'
    yaml_data = read_config(file_path)

  

    print(yaml_data)




    # updating the data with the information of the candidates with the highest score

    # highest scoreing info:

{'Best Model': {'Model_Score': 0, 'Model_name': '', 'Pickle_Locaton': '', 'best_model_parameters': ''}, 'Model03_09_00_25_31_': {'Model_name': 'RandomForestRegressor', 'Model_score': 0.7074716089658655, 'Pickle Locaton': 'c:\\Users\\Lokesh\\Desktop\\Testing project\\Model_container\\01_09_11_56_33_\\GradientBoostingRegressor.pkl', 'best_model_parameters': {'max_depth': 10, 'n_estimators': 200}}, 'Model03_09_00_27_29_': {'Model_name': 'RandomForestRegressor', 'Model_score': 0.7074716089658655, 'Pickle Locaton': 'c:\\Users\\Lokesh\\Desktop\\Testing project\\Model_container\\01_09_11_56_33_\\GradientBoostingRegressor.pkl', 'best_model_parameters': {'max_depth': 10, 'n_estimators': 200}}}


In [4]:
 # reading the config.yaml file
from utility.util import  *
file_path = 'model_status.yaml'
yaml_data = read_config(file_path)


    # updating the data with the information of the candidates with the highest score

    # highest scoreing info:
highest_score = max([ i['Model_score'] for i in yaml_data.values()])
highest_score_model = [ i for i in yaml_data.values()  if i.get('Model_score')==highest_score]


In [11]:
from datetime import datetime

model_info_to_yaml = { f'Model{datetime.now().strftime("%d_%m_%H_%M_%S_")}':
           { 'Model_name':'RandomForestRegressor',
            'Model_score':0.7074716089658655,
            'Pickle Locaton':'c:\\Users\\Lokesh\\Desktop\\Testing project\\Model_container\\01_09_11_56_33_\\GradientBoostingRegressor.pkl',
            'best_model_parameters':'best_model_param'}
        }

 # Sending this information to yaml file
model_entry_to_yaml(model_info_to_yaml)

        # selecting the best model_from model_staus.yaml

best_model_info = get_best_model_from_yaml()

        # getting the pickle file from the best model:
best_model_info['Pickle_Locaton']

'c:\\Users\\Lokesh\\Desktop\\Testing project\\Model_container\\01_09_11_56_33_\\GradientBoostingRegressor.pkl'

In [1]:
import os 

In [7]:
import pickle
Zscore_path = 'C:\\Users\\Lokesh\\Desktop\\Testing project\\Z_Score_Obj\\Z_score.pkl'

with open(Zscore_path, 'rb') as f:
   model =  pickle.load(f)

model.transform([[1234,3423,23,2323,123213, 3232,232,1244]])

C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 6.74887756e+02,  1.57889395e+03, -4.82859560e-01,
        -5.32101079e-02,  4.16736710e+02,  2.45830098e+00,
        -8.50587599e-01,  7.74275012e+02]])

In [1]:
import os
os.getcwd()

'c:\\Users\\Lokesh\\Desktop\\Testing project'

In [3]:
path = 'Logs\\log_2023-07-09-18_24_09.log'

In [8]:
import pickle
model_regression = pickle.load(open('transformed_obj\08_09_17_20_26_\transformation.pkl', 'rb'))

 

model_regression.fit_transform([[12,12,12,12,12,12,12,1222]])


ValueError: embedded null character

In [7]:
import shutil,os

In [33]:
import pickle
z_score_obj = 'Z_Score_Obj\\Z_score.pkl'

with open(z_score_obj, 'rb') as f:
    z_score = pickle.load(f)

pca_obj = 'transformed_obj\\06_09_18_24_54_\\transformation.pkl'

with open(pca_obj, 'rb') as f:
    pca = pickle.load(f)


model_obj = 'Best_model\\08_09_18_03_22_\\RandomForestRegressor.pkl'


with open(model_obj, 'rb') as f:
    model = pickle.load(f)

df = [[12,12,12,12,12,12,12,12]]
z_transformed = z_score.transform(df)

print(z_transformed)
pca_transformed = pca.transform(z_transformed)
model.predict(pca_transformed)

[[ 66.58113951 -11.07389495  -1.41252678  -1.76440941  -1.76374209
   -1.78782118  -1.76883302   5.23464915]]


C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([236953.33163521])

In [17]:
p_model_obj = 'Final_Pipeline\\final_pipeline.pkl'


with open(p_model_obj, 'rb') as f:
    model = pickle.load(f)

model.predict(df)

C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


ValueError: X has 8 features, but RandomForestRegressor is expecting 6 features as input.

In [42]:
import pickle
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define a custom transformer that combines Z-score, PCA, and model prediction
class CustomTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, z_score_path, pca_path, model_path):
        self.z_score_path = z_score_path
        self.pca_path = pca_path
        self.model_path = model_path
        self.z_score = None
        self.pca = None

    def fit(self, X, y=None):
        # Load the Z-score and PCA objects
        with open(self.z_score_path, 'rb') as f:
            self.z_score = pickle.load(f)
        
        with open(self.pca_path, 'rb') as f:
            self.pca = pickle.load(f)
        
        return self

    def transform(self, X):
        if self.z_score is None or self.pca is None:
            raise ValueError("Transformer not fitted")
        
        # Z-score normalization
        z_transformed = self.z_score.transform(X)

        # PCA transformation
        pca_transformed = self.pca.transform(z_transformed)
        return pca_transformed

# Load the model separately
model_path = 'Best_model\\08_09_18_03_22_\\RandomForestRegressor.pkl'
with open(model_path, 'rb') as f:
    model = pickle.load(f)

# Create a pipeline with the custom transformer and the model
pipeline = Pipeline([
    ('custom_transformer', CustomTransformer(z_score_path='Z_Score_Obj\\Z_score.pkl',
                                             pca_path='transformed_obj\\06_09_18_24_54_\\transformation.pkl',
                                             model_path=model_path)),
    ('model', model)  # Add the model as the final step
])

# Example data
df = np.array([[12, 12, 12, 12, 12, 12, 12, 12]])

# Fit the transformer before using it for transformation
pipeline.named_steps['custom_transformer'].fit(df)

# Make predictions using the pipeline
predictions = pipeline.predict(df)

print(predictions)


[236953.33163521]


C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [43]:
import os 
os.getcwd()

'c:\\Users\\Lokesh\\Desktop\\California Housing Price Prediction 2020'

In [ ]:
with open('model_status.yaml', 'r') as file:
            text_content = file.read()

In [21]:
file = 'logs\log_2023-09-09-02_54_53.log'
with open(file , 'rb') as f:
    output = f.read()

In [30]:
get_latest_file('logs')

'logs\\log_2023-09-09-14_38_23.log'

In [29]:
from utility.util import  *
op = get_latest_file('logs')
with open(op , 'r') as f:
    char = f.read()
print(char)

[2023-09-09 14:38:30,354]^;INFO^;14^;__init__.py^;<module>()^;Pandas backend loaded 2.0.3
[2023-09-09 14:38:30,382]^;INFO^;25^;__init__.py^;<module>()^;Numpy backend loaded 1.23.5
[2023-09-09 14:38:30,382]^;INFO^;37^;__init__.py^;<module>()^;Pyspark backend NOT loaded
[2023-09-09 14:38:30,382]^;INFO^;43^;__init__.py^;<module>()^;Python backend loaded
[2023-09-09 14:38:32,832]^;WARNING^;187^;_internal.py^;_log()^; * Debugger is active!
[2023-09-09 14:38:32,840]^;INFO^;187^;_internal.py^;_log()^; * Debugger PIN: 799-365-492



In [ ]:
from output_generation import output_generation
 
op= output_generation([[12,12,12,12,12,12,12,12]])
print(op.generate_output())
  

In [8]:
import os, pickle
z_score_loc = os.path.join(os.getcwd(), 'Pipeline Models and Transformers\z_score_scaling.pkl')
pca_loc  = os.path.join(os.getcwd(), 'Pipeline Models and Transformers\pca.pkl')
model_info  = os.path.join(os.getcwd(), 'Pipeline Models and Transformers\Best_model.pkl')
test_z_score = 'C:\\Users\\Lokesh\\Desktop\\California Housing Price Prediction 2020\\Z_Score_Obj\\Z_score.pkl'


with open (z_score_loc , 'rb') as f:
    z_score = pickle.load(f)


with open (pca_loc , 'rb') as f:
   pca =  pickle.load(f)


with open (model_info , 'rb') as f:
    model = pickle.load(f)


with open (test_z_score , 'rb') as f:
    z_test = pickle.load(f)



# creating a model from all of the files 

data = [[12,12,12,12,12,12,12,12]]
z_scoredf = z_score.transform(data)
print(z_scoredf)

print('old z _score')
df= z_test.transform(data)
print(df)

'''
pca_df = pca.transform(z_scoredf)
output = model.predict(pca_df)
'''



[[21.41556866  2.03789405  1.42184531 17.46569732 -0.74491098 10.68828395]]
old z _score
[[ 65.60787178 -11.02506827  -1.36623947  -1.65011343  -1.64288661
   -1.67245689  -1.66435745   5.16299414]]


C:\Users\Lokesh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


'\npca_df = pca.transform(z_scoredf)\noutput = model.predict(pca_df)\n'

In [ ]:
test_z_score = 'C:\\Users\\Lokesh\\Desktop\\California Housing Price Prediction 2020\\Z_Score_Obj\\Z_score.pkl'
